# Site settings
title: Robert Hargreaves
# email:
# description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.roberthargreaves.com" # the base hostname & protocol for your site
assets: "https://docs.roberthargreaves.net/blog"
twitter_username: robertharg
github_username:  rhargreaves
host: 0.0.0.0
port: 4000
permalink: /:year/:month/:day/:title
paginate: 4
paginate_path: /page:num
gems:
  - jekyll-paginate
tag_page: '/tags'
category_page: '/categories'

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
defaults:
  -
    scope:
        path: ""
        type: "posts"
    values:
      comments: true
